name: Docker Image CI


on:
  workflow_dispatch:  # Manually trigger the workflow
  push:
    paths:
      - 'src/__init__.py'  # Trigger only on changes to src/__init__.py

env:
  IMAGE_NAME: "harrysgb/bus-loc-db-worker"
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Extract version from __init__.py
      id: extract_version
      run: |
        version=$(grep '__version__ =' src/__init__.py | cut -d '"' -f 2)
        if [ -z "$version" ]; then
          echo "Error: Version not found in __init__.py. Aborting workflow."
          exit 1
        fi
        echo "Extracted version: $version"
        echo "::set-output name=version::$version"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "${{ env.IMAGE_NAME }}:${{ steps.extract_version.outputs.version }}" --tag "${{ env.IMAGE_NAME }}:latest"
    - name: Log in to Docker Hub
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
    - name: Push to Docker Hub
      run: docker push "${{ env.IMAGE_NAME }}:${{ steps.extract_version.outputs.version }}"
