name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: "bus-loc-db-worker"
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get latest Docker image tag
      id: get_tag
      run: echo ::set-output name=TAG::$(curl -s "https://registry.hub.docker.com/v1/repositories/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}/tags" | jq -r 'map(.name) | sort | last')
    - name: Increment tag version
      id: increment_tag
      run: echo ::set-output name=TAG::$(($(echo "${{ steps.get_tag.outputs.TAG }}" | sed 's/.*-//')+1))
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "${{ env.IMAGE_NAME }}:${{ steps.increment_tag.outputs.TAG }}"
    - name: Log in to Docker Hub
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
    - name: Push to Docker Hub
      run: docker push "${{ env.IMAGE_NAME }}:${{ steps.increment_tag.outputs.TAG }}"
